//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saplin.CPDT.UICore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L11ns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L11ns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saplin.CPDT.UICore.Localization.L11ns", typeof(L11ns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses standrd OS&apos;s file API (WinAPI on Windows, POSIX on Mac and NDK on Android) to measure the speed of data transfer (in Megabytes per Second) between storage device (HDD, SSD, USB flash drive) and system memory(RAM). API calls are done through .NET Framework/Mono..
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential read and sequential write tests transfer large chunks of data (megabytes) between RAM and Storage. These tests are representative of such disk operstions as large file copying, video recording/encoding/decoding etc..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random tests run for 7 seconds each and do transfers in small chunks (4KB and 32KB) at random positions within the test file. These tests show how file system performance influnce applications&apos; load times, copying multiple small files, runnning database queries etc..
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &apos;Options&apos; section you might find settings which may influence test results:.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Write buffering - influences write test. Write operations use intermediary memory buffer and postpone data commit to latter more convinient time for better performace at a cost of less resiliant writes (e.g. power failure and not commiting to disk write buffer contents)..
        /// </summary>
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • In-memory file cache - influences read tests. Any file operation requires from OS either transfering file data to memory or memory data to disk, OS will keep those memory pages in RAM until there&apos;s preasure for RAM from other apps. In case OS receives subsequent file read/write requests through API it will simply copy the cached memory pages from previous file operstions and not utilize the actual storage device. Turning this option on is essential a test of OS&apos;s file caching subsystem and RAM speed, rath [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations on computers and smartphones are executed by CPU against data which is loaded in system memory (RAM). This memory is not permament and limited in size, that&apos;s why theres always a permanent storage (SSD, HDD, SD Card - aka &quot;disk/drive&quot;). In many cases the performance of the system is determined not only by CPU (whichs are usualy in the spotlight of advertising and target of numerous benchmarks) but by the performance of memory, specifically RAM and storage. In many cases (especially smartphones) o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About7 {
            get {
                return ResourceManager.GetString("About7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is open-source, you might want to check project&apos;s github at:.
        /// </summary>
        public static string About8 {
            get {
                return ResourceManager.GetString("About8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same drive, different aliases.
        /// </summary>
        public static string AndroidSameAliases {
            get {
                return ResourceManager.GetString("AndroidSameAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available drives:.
        /// </summary>
        public static string AvailableDrives {
            get {
                return ResourceManager.GetString("AvailableDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        public static string bps {
            get {
                return ResourceManager.GetString("bps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Esc, B]reak test.
        /// </summary>
        public static string BreakTest {
            get {
                return ResourceManager.GetString("BreakTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Esc, C]lose.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [E]xport test results to CSV.
        /// </summary>
        public static string CsvOption {
            get {
                return ResourceManager.GetString("CsvOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F]ile size:.
        /// </summary>
        public static string FileSizeOption {
            get {
                return ResourceManager.GetString("FileSizeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB free.
        /// </summary>
        public static string GbFree {
            get {
                return ResourceManager.GetString("GbFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB/s.
        /// </summary>
        public static string gbps {
            get {
                return ResourceManager.GetString("gbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [?, H]elp.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start tap on a drive in the list above.
        /// </summary>
        public static string HintAndroid {
            get {
                return ResourceManager.GetString("HintAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start tests click on a drive in the list above or press number key.
        /// </summary>
        public static string HintMisc {
            get {
                return ResourceManager.GetString("HintMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string kb {
            get {
                return ResourceManager.GetString("kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB/s.
        /// </summary>
        public static string kbps {
            get {
                return ResourceManager.GetString("kbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [L]anguage:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/s.
        /// </summary>
        public static string mbps {
            get {
                return ResourceManager.GetString("mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-[m]emory file cache:.
        /// </summary>
        public static string MemCacheOption {
            get {
                return ResourceManager.GetString("MemCacheOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory copy.
        /// </summary>
        public static string MemCopyTest {
            get {
                return ResourceManager.GetString("MemCopyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem. copy.
        /// </summary>
        public static string MemCopyTestShort {
            get {
                return ResourceManager.GetString("MemCopyTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Off).
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (On).
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O]ptions.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - pick any drive to run perofrmance test against it.
        /// </summary>
        public static string PickDrive {
            get {
                return ResourceManager.GetString("PickDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/maxim-saplin/CrossPlatformDiskTest.
        /// </summary>
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Q]uit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating application....
        /// </summary>
        public static string Quiting {
            get {
                return ResourceManager.GetString("Quiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random read.
        /// </summary>
        public static string RandomReadTest {
            get {
                return ResourceManager.GetString("RandomReadTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand. read.
        /// </summary>
        public static string RandomReadTestShort {
            get {
                return ResourceManager.GetString("RandomReadTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random write.
        /// </summary>
        public static string RandomWriteTest {
            get {
                return ResourceManager.GetString("RandomWriteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand. write.
        /// </summary>
        public static string RandomWriteTestShort {
            get {
                return ResourceManager.GetString("RandomWriteTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [R]efresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential read.
        /// </summary>
        public static string SequentialReadTest {
            get {
                return ResourceManager.GetString("SequentialReadTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq. read.
        /// </summary>
        public static string SequentialReadTestShort {
            get {
                return ResourceManager.GetString("SequentialReadTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential write.
        /// </summary>
        public static string SequentialWriteTest {
            get {
                return ResourceManager.GetString("SequentialWriteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq. write.
        /// </summary>
        public static string SequentialWriteTestShort {
            get {
                return ResourceManager.GetString("SequentialWriteTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAKING TEST.
        /// </summary>
        public static string StatusBreakingTest {
            get {
                return ResourceManager.GetString("StatusBreakingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test has completed execution. Test file deleted.
        /// </summary>
        public static string StatusTestCompleted {
            get {
                return ResourceManager.GetString("StatusTestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution completed. Test results exported to CVS file.
        /// </summary>
        public static string StatusTestCsvCompleted {
            get {
                return ResourceManager.GetString("StatusTestCsvCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution interrupted due to error.
        /// </summary>
        public static string StatusTestError {
            get {
                return ResourceManager.GetString("StatusTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution interrupted. Test file deleted.
        /// </summary>
        public static string StatusTestInterrupted {
            get {
                return ResourceManager.GetString("StatusTestInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing test data in RAM....
        /// </summary>
        public static string TestInitMemBuffer {
            get {
                return ResourceManager.GetString("TestInitMemBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory.
        /// </summary>
        public static string TestNotEnoughMemory {
            get {
                return ResourceManager.GetString("TestNotEnoughMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging memory cache....
        /// </summary>
        public static string TestPurgingMemCache {
            get {
                return ResourceManager.GetString("TestPurgingMemCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running test....
        /// </summary>
        public static string TestRunning {
            get {
                return ResourceManager.GetString("TestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test started.
        /// </summary>
        public static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} GB. Free space: {1:0.0} GB. Write Buffering: {2}. In-memory file cache: {3}.
        /// </summary>
        public static string TestSummaryFormatString {
            get {
                return ResourceManager.GetString("TestSummaryFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming up....
        /// </summary>
        public static string TestWarmigUp {
            get {
                return ResourceManager.GetString("TestWarmigUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [W]hite theme (restart required).
        /// </summary>
        public static string WhiteTheme {
            get {
                return ResourceManager.GetString("WhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write [b]uffering:.
        /// </summary>
        public static string WriteBufferingOption {
            get {
                return ResourceManager.GetString("WriteBufferingOption", resourceCulture);
            }
        }
    }
}
