//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saplin.CPDT.UICore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L11ns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L11ns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saplin.CPDT.UICore.Localization.L11ns", typeof(L11ns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses standard OS&apos;s file API (WinAPI on Windows, POSIX on Mac and NDK on Android) to measure the speed of data transfer (in Megabytes per Second) between storage device (HDD, SSD, USB flash drive) and system memory(RAM). API calls are done through .NET Framework/Mono..
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each of the tests is accompanied by a graph. Sequential and memory copy tests show immediate throughputs (measure for a single block) plotted against blocks&apos; positions. I.e. you can see how speed changes with the progression of the reads/writes toward end of test file. E.g. you might notice that sometimes storage shows lags at the begining of the operation (typical for Android). Random tests show histogram, where each individual&apos;s block throughput is placed into a specific bin/range, and the graph shows how [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About10 {
            get {
                return ResourceManager.GetString("About10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential read and sequential write tests transfer large chunks of data (megabytes) between RAM and Storage. These tests are representative of such disk operations as large file copying, video recording/encoding/decoding etc..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random tests run for 7 seconds each and do transfers in small chunks (4KB and 32KB) at random positions within the test file. These tests show how file system performance influence applications&apos; load times, copying multiple small files, running database queries etc..
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &apos;Options&apos; section you might find settings which may influence test results:.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Write buffering - influences write test. Write operations use intermediary memory buffer and postpone data commit to latter more convenient time for better performance at a cost of less resilient writes (e.g. power failure and not committing to disk write buffer contents)..
        /// </summary>
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • In-memory file cache - influences read tests. Any file operation requires from OS either transferring file data to memory or memory data to disk, OS will keep those memory pages in RAM until there&apos;s pressure for RAM from other apps. In case OS receives subsequent file read/write requests through API it will simply copy the cached memory pages from previous file operations and not utilize the actual storage device. Turning this option on is essential a test of OS&apos;s file caching subsystem and RAM speed, rat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations on computers and smartphones are executed by processor (CPU) against data which is loaded in system memory (RAM). This memory is not permanent and limited in size, that&apos;s why theres always a permanent storage (SSD, HDD, SD Card - aka &quot;disk/drive&quot;). In many cases the performance of the system is determined not only by CPU (which are usually in the spotlight of advertising and target of numerous benchmarks) but by the performance of memory, specifically RAM and storage. Official specs (especially w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About7 {
            get {
                return ResourceManager.GetString("About7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is open-source, you might want to check project&apos;s GitHub at:.
        /// </summary>
        public static string About8 {
            get {
                return ResourceManager.GetString("About8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the app for different platforms (Windows, macOS, Android/APK) at the following link:.
        /// </summary>
        public static string About9 {
            get {
                return ResourceManager.GetString("About9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same drive, different aliases.
        /// </summary>
        public static string AndroidSameAliases {
            get {
                return ResourceManager.GetString("AndroidSameAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available drives:.
        /// </summary>
        public static string AvailableDrives {
            get {
                return ResourceManager.GetString("AvailableDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        public static string bps {
            get {
                return ResourceManager.GetString("bps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Esc, B]reak.
        /// </summary>
        public static string BreakTest {
            get {
                return ResourceManager.GetString("BreakTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant test some drives. {0}GB free space required.
        /// </summary>
        public static string CantTestNotEnough {
            get {
                return ResourceManager.GetString("CantTestNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CClose {
            get {
                return ResourceManager.GetString("CClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Esc, C]lose.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⇆ Compare .
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [E]xport test results to CSV.
        /// </summary>
        public static string CsvOption {
            get {
                return ResourceManager.GetString("CsvOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [D]atabase.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Database isn&apos;t available. Check internet connection.
        /// </summary>
        public static string DbNotAvailable {
            get {
                return ResourceManager.GetString("DbNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maxim-saplin.github.io/cpdt_results/?download=&amp;lang=en&amp;app=.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maxim-saplin.github.io/cpdt_results/?download=.
        /// </summary>
        public static string DownloadLinkShort {
            get {
                return ResourceManager.GetString("DownloadLinkShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F]ile size:.
        /// </summary>
        public static string FileSizeOption {
            get {
                return ResourceManager.GetString("FileSizeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB free.
        /// </summary>
        public static string GbFree {
            get {
                return ResourceManager.GetString("GbFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB/s.
        /// </summary>
        public static string gbps {
            get {
                return ResourceManager.GetString("gbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [?, H]elp.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start tap on a drive in the list above.
        /// </summary>
        public static string HintAndroid {
            get {
                return ResourceManager.GetString("HintAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start tests click on a drive in the list above or press number key.
        /// </summary>
        public static string HintMisc {
            get {
                return ResourceManager.GetString("HintMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while fetching a list of drives/partitions avaialable. Tests cant be executed..
        /// </summary>
        public static string InitDrivesError {
            get {
                return ResourceManager.GetString("InitDrivesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string kb {
            get {
                return ResourceManager.GetString("kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB/s.
        /// </summary>
        public static string kbps {
            get {
                return ResourceManager.GetString("kbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [L]anguage:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/s.
        /// </summary>
        public static string mbps {
            get {
                return ResourceManager.GetString("mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-[m]emory file cache:.
        /// </summary>
        public static string MemCacheOption {
            get {
                return ResourceManager.GetString("MemCacheOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory copy.
        /// </summary>
        public static string MemCopyTest {
            get {
                return ResourceManager.GetString("MemCopyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem.
        ///copy.
        /// </summary>
        public static string MemCopyTestShort {
            get {
                return ResourceManager.GetString("MemCopyTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem. copy.
        /// </summary>
        public static string MemCopyTestShortNB {
            get {
                return ResourceManager.GetString("MemCopyTestShortNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ModeH {
            get {
                return ResourceManager.GetString("ModeH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not avaialble.
        /// </summary>
        public static string NotAccessibleDriveHint {
            get {
                return ResourceManager.GetString("NotAccessibleDriveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not enough.
        /// </summary>
        public static string NotEnoughSpaceHint {
            get {
                return ResourceManager.GetString("NotEnoughSpaceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Off).
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (On).
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O]ptions.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - pick any drive to run perofrmance test against it.
        /// </summary>
        public static string PickDrive {
            get {
                return ResourceManager.GetString("PickDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/maxim-saplin/CrossPlatformDiskTest.
        /// </summary>
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Q]uit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating application....
        /// </summary>
        public static string Quiting {
            get {
                return ResourceManager.GetString("Quiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random read.
        /// </summary>
        public static string RandomReadTest {
            get {
                return ResourceManager.GetString("RandomReadTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand.
        ///read.
        /// </summary>
        public static string RandomReadTestShort {
            get {
                return ResourceManager.GetString("RandomReadTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand. read.
        /// </summary>
        public static string RandomReadTestShortNB {
            get {
                return ResourceManager.GetString("RandomReadTestShortNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random write.
        /// </summary>
        public static string RandomWriteTest {
            get {
                return ResourceManager.GetString("RandomWriteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand.
        ///write.
        /// </summary>
        public static string RandomWriteTestShort {
            get {
                return ResourceManager.GetString("RandomWriteTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand. write.
        /// </summary>
        public static string RandomWriteTestShortNB {
            get {
                return ResourceManager.GetString("RandomWriteTestShortNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [R]efresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential read.
        /// </summary>
        public static string SequentialReadTest {
            get {
                return ResourceManager.GetString("SequentialReadTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        ///read.
        /// </summary>
        public static string SequentialReadTestShort {
            get {
                return ResourceManager.GetString("SequentialReadTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq. read.
        /// </summary>
        public static string SequentialReadTestShortNB {
            get {
                return ResourceManager.GetString("SequentialReadTestShortNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential write.
        /// </summary>
        public static string SequentialWriteTest {
            get {
                return ResourceManager.GetString("SequentialWriteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        ///write.
        /// </summary>
        public static string SequentialWriteTestShort {
            get {
                return ResourceManager.GetString("SequentialWriteTestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq. write.
        /// </summary>
        public static string SequentialWriteTestShortNB {
            get {
                return ResourceManager.GetString("SequentialWriteTestShortNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬑Share⬏.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDT Benchmark: https://play.google.com/store/apps/details?id=com.Saplin.CPDT.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [M]ore.
        /// </summary>
        public static string SimpleUI_More {
            get {
                return ResourceManager.GetString("SimpleUI_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or see.
        /// </summary>
        public static string SimpleUI_OrSee {
            get {
                return ResourceManager.GetString("SimpleUI_OrSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a.
        /// </summary>
        public static string SimpleUI_StartA {
            get {
                return ResourceManager.GetString("SimpleUI_StartA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [T]est.
        /// </summary>
        public static string SimpleUI_Test {
            get {
                return ResourceManager.GetString("SimpleUI_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S]imple UI.
        /// </summary>
        public static string SimpleUIOption {
            get {
                return ResourceManager.GetString("SimpleUIOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAKING TEST.
        /// </summary>
        public static string StatusBreakingTest {
            get {
                return ResourceManager.GetString("StatusBreakingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test has completed execution. Test file deleted.
        /// </summary>
        public static string StatusTestCompleted {
            get {
                return ResourceManager.GetString("StatusTestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution completed. Test results exported to CSV file.
        /// </summary>
        public static string StatusTestCsvCompleted {
            get {
                return ResourceManager.GetString("StatusTestCsvCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution interrupted due to error.
        /// </summary>
        public static string StatusTestError {
            get {
                return ResourceManager.GetString("StatusTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution interrupted. Test file deleted.
        /// </summary>
        public static string StatusTestInterrupted {
            get {
                return ResourceManager.GetString("StatusTestInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing test data in RAM....
        /// </summary>
        public static string TestInitMemBuffer {
            get {
                return ResourceManager.GetString("TestInitMemBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory.
        /// </summary>
        public static string TestNotEnoughMemory {
            get {
                return ResourceManager.GetString("TestNotEnoughMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0} of {1}.
        /// </summary>
        public static string TestOf {
            get {
                return ResourceManager.GetString("TestOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging memory cache....
        /// </summary>
        public static string TestPurgingMemCache {
            get {
                return ResourceManager.GetString("TestPurgingMemCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running test....
        /// </summary>
        public static string TestRunning {
            get {
                return ResourceManager.GetString("TestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test started.
        /// </summary>
        public static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} GB. Free space: {1:0.0} GB. Write Buffering: {2}. In-memory file cache: {3}.
        /// </summary>
        public static string TestSummaryFormatString {
            get {
                return ResourceManager.GetString("TestSummaryFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:{0}GB Free:{1:0.0}GB W.Buffering:{2} Cache:{3}.
        /// </summary>
        public static string TestSummaryShortFormatString {
            get {
                return ResourceManager.GetString("TestSummaryShortFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done {0:0}%.
        /// </summary>
        public static string TestTotal {
            get {
                return ResourceManager.GetString("TestTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming up....
        /// </summary>
        public static string TestWarmigUp {
            get {
                return ResourceManager.GetString("TestWarmigUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [W]hite theme (restart required).
        /// </summary>
        public static string WhiteTheme {
            get {
                return ResourceManager.GetString("WhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write [b]uffering:.
        /// </summary>
        public static string WriteBufferingOption {
            get {
                return ResourceManager.GetString("WriteBufferingOption", resourceCulture);
            }
        }
    }
}
