//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saplin.CPDT.UICore.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L11ns {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L11ns() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Saplin.CPDT.UICore.Localization.L11ns", typeof(L11ns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        public static string About7 {
            get {
                return ResourceManager.GetString("About7", resourceCulture);
            }
        }
        
        public static string About8 {
            get {
                return ResourceManager.GetString("About8", resourceCulture);
            }
        }
        
        public static string AndroidSameAliases {
            get {
                return ResourceManager.GetString("AndroidSameAliases", resourceCulture);
            }
        }
        
        public static string AvailableDrives {
            get {
                return ResourceManager.GetString("AvailableDrives", resourceCulture);
            }
        }
        
        public static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        public static string bps {
            get {
                return ResourceManager.GetString("bps", resourceCulture);
            }
        }
        
        public static string BreakTest {
            get {
                return ResourceManager.GetString("BreakTest", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CsvOption {
            get {
                return ResourceManager.GetString("CsvOption", resourceCulture);
            }
        }
        
        public static string FileSizeOption {
            get {
                return ResourceManager.GetString("FileSizeOption", resourceCulture);
            }
        }
        
        public static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        public static string GbFree {
            get {
                return ResourceManager.GetString("GbFree", resourceCulture);
            }
        }
        
        public static string gbps {
            get {
                return ResourceManager.GetString("gbps", resourceCulture);
            }
        }
        
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        public static string HintAndroid {
            get {
                return ResourceManager.GetString("HintAndroid", resourceCulture);
            }
        }
        
        public static string HintMisc {
            get {
                return ResourceManager.GetString("HintMisc", resourceCulture);
            }
        }
        
        public static string kb {
            get {
                return ResourceManager.GetString("kb", resourceCulture);
            }
        }
        
        public static string kbps {
            get {
                return ResourceManager.GetString("kbps", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        public static string mb {
            get {
                return ResourceManager.GetString("mb", resourceCulture);
            }
        }
        
        public static string mbps {
            get {
                return ResourceManager.GetString("mbps", resourceCulture);
            }
        }
        
        public static string MemCacheOption {
            get {
                return ResourceManager.GetString("MemCacheOption", resourceCulture);
            }
        }
        
        public static string MemCopyTest {
            get {
                return ResourceManager.GetString("MemCopyTest", resourceCulture);
            }
        }
        
        public static string MemCopyTestShort {
            get {
                return ResourceManager.GetString("MemCopyTestShort", resourceCulture);
            }
        }
        
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        public static string PickDrive {
            get {
                return ResourceManager.GetString("PickDrive", resourceCulture);
            }
        }
        
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        public static string Quiting {
            get {
                return ResourceManager.GetString("Quiting", resourceCulture);
            }
        }
        
        public static string RandomReadTest {
            get {
                return ResourceManager.GetString("RandomReadTest", resourceCulture);
            }
        }
        
        public static string RandomReadTestShort {
            get {
                return ResourceManager.GetString("RandomReadTestShort", resourceCulture);
            }
        }
        
        public static string RandomWriteTest {
            get {
                return ResourceManager.GetString("RandomWriteTest", resourceCulture);
            }
        }
        
        public static string RandomWriteTestShort {
            get {
                return ResourceManager.GetString("RandomWriteTestShort", resourceCulture);
            }
        }
        
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        public static string SequentialReadTest {
            get {
                return ResourceManager.GetString("SequentialReadTest", resourceCulture);
            }
        }
        
        public static string SequentialReadTestShort {
            get {
                return ResourceManager.GetString("SequentialReadTestShort", resourceCulture);
            }
        }
        
        public static string SequentialWriteTest {
            get {
                return ResourceManager.GetString("SequentialWriteTest", resourceCulture);
            }
        }
        
        public static string SequentialWriteTestShort {
            get {
                return ResourceManager.GetString("SequentialWriteTestShort", resourceCulture);
            }
        }
        
        public static string StatusBreakingTest {
            get {
                return ResourceManager.GetString("StatusBreakingTest", resourceCulture);
            }
        }
        
        public static string StatusTestCompleted {
            get {
                return ResourceManager.GetString("StatusTestCompleted", resourceCulture);
            }
        }
        
        public static string StatusTestCsvCompleted {
            get {
                return ResourceManager.GetString("StatusTestCsvCompleted", resourceCulture);
            }
        }
        
        public static string StatusTestError {
            get {
                return ResourceManager.GetString("StatusTestError", resourceCulture);
            }
        }
        
        public static string StatusTestInterrupted {
            get {
                return ResourceManager.GetString("StatusTestInterrupted", resourceCulture);
            }
        }
        
        public static string TestInitMemBuffer {
            get {
                return ResourceManager.GetString("TestInitMemBuffer", resourceCulture);
            }
        }
        
        public static string TestNotEnoughMemory {
            get {
                return ResourceManager.GetString("TestNotEnoughMemory", resourceCulture);
            }
        }
        
        public static string TestPurgingMemCache {
            get {
                return ResourceManager.GetString("TestPurgingMemCache", resourceCulture);
            }
        }
        
        public static string TestRunning {
            get {
                return ResourceManager.GetString("TestRunning", resourceCulture);
            }
        }
        
        public static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
        
        public static string TestSummaryFormatString {
            get {
                return ResourceManager.GetString("TestSummaryFormatString", resourceCulture);
            }
        }
        
        public static string TestWarmigUp {
            get {
                return ResourceManager.GetString("TestWarmigUp", resourceCulture);
            }
        }
        
        public static string WhiteTheme {
            get {
                return ResourceManager.GetString("WhiteTheme", resourceCulture);
            }
        }
        
        public static string WriteBufferingOption {
            get {
                return ResourceManager.GetString("WriteBufferingOption", resourceCulture);
            }
        }
        
        public static string CClose {
            get {
                return ResourceManager.GetString("CClose", resourceCulture);
            }
        }
        
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        public static string DbNotAvailable {
            get {
                return ResourceManager.GetString("DbNotAvailable", resourceCulture);
            }
        }
    }
}
